baseURL = "https://loredous.github.io/open-packet/"
languageCode = "en-us"
title = "open-packet Documentation"
enableGitInfo = true

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  sans_serif_font = "Inter"
  secondary_font  = "Inter"
  mono_font       = "Fira Code"

  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  [params.footer]
    copyright = "© :YEAR: open-packet contributors. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"

  [params.social]
    github = "loredous/open-packet"

  [params.docs]
    title           = "open-packet Documentation"
    pathName        = "docs"
    themeColor      = "cyan"
    darkMode        = true
    prism           = true
    prismTheme      = "lotusdocs"
    repoURL         = "https://github.com/loredous/open-packet"
    repoBranch      = "main"
    editPage        = true
    lastMod         = true
    lastModRelative = true
    sidebarIcons    = true
    breadcrumbs     = true
    backToTop       = true
    toc             = true
    tocMobile       = true
    scrollSpy       = true
    descriptions    = true
    titleIcon       = true
    navDesc         = true
    navDescTrunc    = 30
    listDescTrunc   = 100
    intLinkTooltip  = true

  [params.flexsearch]
    enabled      = true
    tokenize     = "full"
    optimize     = true
    cache        = 100
    minQueryChar = 3
    maxResult    = 5

[menu]
  [[menu.primary]]
    name       = "Docs"
    url        = "docs/"
    identifier = "docs"
    weight     = 10

  [[menu.primary]]
    name       = "GitHub"
    url        = "https://github.com/loredous/open-packet"
    identifier = "github"
    weight     = 20
